### ISSUE TITLE
[Bug]: Car park out scenario not working in second map

### ISSUE THREAD

**Issue by robertik10** [una-auxme/paf23#172]
### Current Behavior

Car doesn't seem to be able to park out of it's parking spot in the second map

### Expected Behavior

Car should be park out on the second map just as good as on the first map 

### How to reproduce the issue

- let the car drive till the first map stops and the second map starts
- right at the beginning it seems like the park out scenario is inactive
-> could be due to the fact, that the behaviour tree doesn't work properly after some time
   OR: the park out scenario variable has to reset when we spawn on another map

**Comment by samuelkuehnel** [comment]
The problem is that the behavior is not reset. I currently can't test the fix because my memory usage would raise too high. Can you try it out on your PC? @robertik10

**Comment by samuelkuehnel** [comment]
When trying to reproduce the situation, I found the behavior working (video). The problem that the vehicle doesn't leave the parking space also occurred sometimes on the first map. The problem is that the vehicle starts driving seconds before the initial trajectory is calculated. Therefore the steering doesn't work and we stay inside the parking space. You can observe in the rviz window that we start driving just before the green trajectory is visible. This bug is fixed in @JuliusMiller's branch where the curve speed is considered. 
[BugFix_edited.webm](https://github.com/una-auxme/paf23/assets/51356601/123a7a6e-ae64-4506-9367-8d8ed510436c)

Therefore I will delete the branch from this issue.

**Comment by robertik10** [comment]
Alright sounds good to me, great job!
